In [10]:
import pandas as pd

df = pd.read_csv('roto-point.csv', index_col=0)
df

,FG%,FT%,3PTM,PTS,OREB,REB,AST,ST,BLK,TO,A/T,Total
Team,,,,,,,,,,,,
Zephyr,15.0,10.0,9.0,4.0,1.5,4.0,2.0,16.0,7.5,17.5,12.0,98.5
Cupid's Arrow,6.0,14.0,10.5,16.0,12.0,9.0,18.0,9.5,5.0,2.0,11.0,113.0
天王,16.5,1.0,8.0,14.0,10.0,7.0,14.0,7.0,1.0,11.5,16.0,106.0
JamarrChase,5.0,3.0,14.0,12.0,13.0,15.0,15.0,13.0,2.0,7.5,14.0,113.5
Mars,16.5,17.5,17.0,17.0,18.0,13.0,17.0,5.5,7.5,3.0,13.0,145.0
max,3.0,7.0,4.0,9.0,11.0,14.0,10.0,5.5,15.0,5.0,3.5,87.0
Melo,4.0,15.5,10.5,11.0,5.0,11.0,7.0,9.5,15.0,9.0,7.0,104.5
Prince,1.0,13.0,16.0,6.0,8.5,6.0,4.0,14.5,11.0,13.0,8.0,101.0
Sin,8.0,8.0,14.0,13.0,4.0,3.0,13.0,4.0,3.5,11.5,15.0,97.0
72wins,7.0,6.0,3.0,2.0,8.5,5.0,1.0,17.0,17.0,14.0,1.0,81.5
蹩脚马_Alpha,10.0,11.0,5.5,10.0,7.0,10.0,5.0,2.0,9.5,7.5,5.0,82.5
首席NBA,11.0,15.5,14.0,5.0,3.0,2.0,12.0,3.0,12.0,17.5,18.0,113.0
karsitty,18.0,9.0,18.0,18.0,15.0,16.0,16.0,18.0,18.0,1.0,6.0,153.0
灰灰,2.0,17.5,5.5,3.0,1.5,1.0,11.0,9.5,3.5,16.0,17.0,87.5
我还想要一只冰墩墩,13.0,12.0,12.0,15.0,6.0,12.0,6.0,12.0,9.5,6.0,3.5,107.0
SLV,12.0,5.0,7.0,8.0,16.5,18.0,8.0,14.5,6.0,4.0,2.0,101.0
cao's Ingenious Team,14.0,2.0,1.0,1.0,14.0,8.0,9.0,1.0,13.0,10.0,9.0,82.0
lydia,9.0,4.0,2.0,7.0,16.5,17.0,3.0,9.5,15.0,15.0,10.0,108.0

In [52]:
import numpy as np

# green background
style_top = 'background-color:#e6ffe6'

# red background
style_bottom = 'background-color:#ffe6e6'

def highlight_max_min(s):
    """
    Highlight the maximum value in a Series with a green background
    and the minimum value with a red background.
    
    Parameters
    ----------
    s : pandas.Series
        The Series to be styled.
    
    Returns
    -------
    pandas.Series
        The styled Series with the maximum and minimum values highlighted.
    """
    is_max = s == s.max()
    is_min = s == s.min()
    return [style_top if v else style_bottom if m else '' for v, m in zip(is_max, is_min)]

def remove_trailing_zeros(x):
    """
    Remove trailing zeros from a number.
    
    Parameters
    ----------
    x : float
        The number to be formatted.
    
    Returns
    -------
    str
        The formatted number as a string without trailing zeros.
    """
    return ('%f' % x).rstrip('0').rstrip('.') if isinstance(x, float) else x

    
# Apply the highlight_min function to each column
styled_df = df.style.apply(highlight_max_min, axis=0).format(remove_trailing_zeros).set_table_styles(
        [{'selector': 'thead th', 'props': [('background-color', '#f7f7f9'), ('color', '#333333')]}]
    ).set_properties(**{'text-align': 'right', 'width': '50px'}).set_caption("Styled DataFrame")

# Display the styled DataFrame
styled_df

In [54]:
# Save styled DataFrame as HTML
html = styled_df.to_html(col_space=60, na_rep='', bold_rows=False, notebook=True)
print(html)

<style type="text/css">
#T_73650 thead th {
  background-color: #f7f7f9;
  color: #333333;
}
#T_73650_row0_col0, #T_73650_row0_col1, #T_73650_row0_col2, #T_73650_row0_col3, #T_73650_row0_col5, #T_73650_row0_col6, #T_73650_row0_col7, #T_73650_row0_col8, #T_73650_row0_col10, #T_73650_row0_col11, #T_73650_row1_col0, #T_73650_row1_col1, #T_73650_row1_col2, #T_73650_row1_col3, #T_73650_row1_col4, #T_73650_row1_col5, #T_73650_row1_col7, #T_73650_row1_col8, #T_73650_row1_col9, #T_73650_row1_col10, #T_73650_row1_col11, #T_73650_row2_col0, #T_73650_row2_col2, #T_73650_row2_col3, #T_73650_row2_col4, #T_73650_row2_col5, #T_73650_row2_col6, #T_73650_row2_col7, #T_73650_row2_col9, #T_73650_row2_col10, #T_73650_row2_col11, #T_73650_row3_col0, #T_73650_row3_col1, #T_73650_row3_col2, #T_73650_row3_col3, #T_73650_row3_col4, #T_73650_row3_col5, #T_73650_row3_col6, #T_73650_row3_col7, #T_73650_row3_col8, #T_73650_row3_col9, #T_73650_row3_col10, #T_73650_row3_col11, #T_73650_row4_col0, #T_73650_row4_col2, #T_73650_row4_col3, #T_73650_row4_col5, #T_73650_row4_col6, #T_73650_row4_col7, #T_73650_row4_col8, #T_73650_row4_col9, #T_73650_row4_col10, #T_73650_row4_col11, #T_73650_row5_col0, #T_73650_row5_col1, #T_73650_row5_col2, #T_73650_row5_col3, #T_73650_row5_col4, #T_73650_row5_col5, #T_73650_row5_col6, #T_73650_row5_col7, #T_73650_row5_col8, #T_73650_row5_col9, #T_73650_row5_col10, #T_73650_row5_col11, #T_73650_row6_col0, #T_73650_row6_col1, #T_73650_row6_col2, #T_73650_row6_col3, #T_73650_row6_col4, #T_73650_row6_col5, #T_73650_row6_col6, #T_73650_row6_col7, #T_73650_row6_col8, #T_73650_row6_col9, #T_73650_row6_col10, #T_73650_row6_col11, #T_73650_row7_col1, #T_73650_row7_col2, #T_73650_row7_col3, #T_73650_row7_col4, #T_73650_row7_col5, #T_73650_row7_col6, #T_73650_row7_col7, #T_73650_row7_col8, #T_73650_row7_col9, #T_73650_row7_col10, #T_73650_row7_col11, #T_73650_row8_col0, #T_73650_row8_col1, #T_73650_row8_col2, #T_73650_row8_col3, #T_73650_row8_col4, #T_73650_row8_col5, #T_73650_row8_col6, #T_73650_row8_col7, #T_73650_row8_col8, #T_73650_row8_col9, #T_73650_row8_col10, #T_73650_row8_col11, #T_73650_row9_col0, #T_73650_row9_col1, #T_73650_row9_col2, #T_73650_row9_col3, #T_73650_row9_col4, #T_73650_row9_col5, #T_73650_row9_col7, #T_73650_row9_col8, #T_73650_row9_col9, #T_73650_row10_col0, #T_73650_row10_col1, #T_73650_row10_col2, #T_73650_row10_col3, #T_73650_row10_col4, #T_73650_row10_col5, #T_73650_row10_col6, #T_73650_row10_col7, #T_73650_row10_col8, #T_73650_row10_col9, #T_73650_row10_col10, #T_73650_row10_col11, #T_73650_row11_col0, #T_73650_row11_col1, #T_73650_row11_col2, #T_73650_row11_col3, #T_73650_row11_col4, #T_73650_row11_col5, #T_73650_row11_col6, #T_73650_row11_col7, #T_73650_row11_col8, #T_73650_row11_col11, #T_73650_row12_col1, #T_73650_row12_col4, #T_73650_row12_col5, #T_73650_row12_col6, #T_73650_row12_col10, #T_73650_row13_col0, #T_73650_row13_col2, #T_73650_row13_col3, #T_73650_row13_col6, #T_73650_row13_col7, #T_73650_row13_col8, #T_73650_row13_col9, #T_73650_row13_col10, #T_73650_row13_col11, #T_73650_row14_col0, #T_73650_row14_col1, #T_73650_row14_col2, #T_73650_row14_col3, #T_73650_row14_col4, #T_73650_row14_col5, #T_73650_row14_col6, #T_73650_row14_col7, #T_73650_row14_col8, #T_73650_row14_col9, #T_73650_row14_col10, #T_73650_row14_col11, #T_73650_row15_col0, #T_73650_row15_col1, #T_73650_row15_col2, #T_73650_row15_col3, #T_73650_row15_col4, #T_73650_row15_col6, #T_73650_row15_col7, #T_73650_row15_col8, #T_73650_row15_col9, #T_73650_row15_col10, #T_73650_row15_col11, #T_73650_row16_col0, #T_73650_row16_col1, #T_73650_row16_col4, #T_73650_row16_col5, #T_73650_row16_col6, #T_73650_row16_col8, #T_73650_row16_col9, #T_73650_row16_col10, #T_73650_row16_col11, #T_73650_row17_col0, #T_73650_row17_col1, #T_73650_row17_col2, #T_73650_row17_col3, #T_73650_row17_col4, #T_73650_row17_col5, #T_73650_row17_col6, #T_73650_row17_col7, #T_73650_row17_col8, #T_73650_row17_col9, #T_73650_row17_col10, #T_73650_row17_col11 {
  text-align: right;
  width: 50px;
}
#T_73650_row0_col4, #T_73650_row2_col1, #T_73650_row2_col8, #T_73650_row7_col0, #T_73650_row9_col6, #T_73650_row9_col10, #T_73650_row9_col11, #T_73650_row12_col9, #T_73650_row13_col4, #T_73650_row13_col5, #T_73650_row16_col2, #T_73650_row16_col3, #T_73650_row16_col7 {
  background-color: #ffe6e6;
  text-align: right;
  width: 50px;
}
#T_73650_row0_col9, #T_73650_row1_col6, #T_73650_row4_col1, #T_73650_row4_col4, #T_73650_row11_col9, #T_73650_row11_col10, #T_73650_row12_col0, #T_73650_row12_col2, #T_73650_row12_col3, #T_73650_row12_col7, #T_73650_row12_col8, #T_73650_row12_col11, #T_73650_row13_col1, #T_73650_row15_col5 {
  background-color: #e6ffe6;
  text-align: right;
  width: 50px;
}
</style>
<table id="T_73650">
  <caption>Styled DataFrame</caption>
  <thead>
    <tr>
      <th class="blank level0" >&nbsp;</th>
      <th id="T_73650_level0_col0" class="col_heading level0 col0" >FG%</th>
      <th id="T_73650_level0_col1" class="col_heading level0 col1" >FT%</th>
      <th id="T_73650_level0_col2" class="col_heading level0 col2" >3PTM</th>
      <th id="T_73650_level0_col3" class="col_heading level0 col3" >PTS</th>
      <th id="T_73650_level0_col4" class="col_heading level0 col4" >OREB</th>
      <th id="T_73650_level0_col5" class="col_heading level0 col5" >REB</th>
      <th id="T_73650_level0_col6" class="col_heading level0 col6" >AST</th>
      <th id="T_73650_level0_col7" class="col_heading level0 col7" >ST</th>
      <th id="T_73650_level0_col8" class="col_heading level0 col8" >BLK</th>
      <th id="T_73650_level0_col9" class="col_heading level0 col9" >TO</th>
      <th id="T_73650_level0_col10" class="col_heading level0 col10" >A/T</th>
      <th id="T_73650_level0_col11" class="col_heading level0 col11" >Total</th>
    </tr>
    <tr>
      <th class="index_name level0" >Team</th>
      <th class="blank col0" >&nbsp;</th>
      <th class="blank col1" >&nbsp;</th>
      <th class="blank col2" >&nbsp;</th>
      <th class="blank col3" >&nbsp;</th>
      <th class="blank col4" >&nbsp;</th>
      <th class="blank col5" >&nbsp;</th>
      <th class="blank col6" >&nbsp;</th>
      <th class="blank col7" >&nbsp;</th>
      <th class="blank col8" >&nbsp;</th>
      <th class="blank col9" >&nbsp;</th>
      <th class="blank col10" >&nbsp;</th>
      <th class="blank col11" >&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th id="T_73650_level0_row0" class="row_heading level0 row0" >Zephyr</th>
      <td id="T_73650_row0_col0" class="data row0 col0" >15</td>
      <td id="T_73650_row0_col1" class="data row0 col1" >10</td>
      <td id="T_73650_row0_col2" class="data row0 col2" >9</td>
      <td id="T_73650_row0_col3" class="data row0 col3" >4</td>
      <td id="T_73650_row0_col4" class="data row0 col4" >1.5</td>
      <td id="T_73650_row0_col5" class="data row0 col5" >4</td>
      <td id="T_73650_row0_col6" class="data row0 col6" >2</td>
      <td id="T_73650_row0_col7" class="data row0 col7" >16</td>
      <td id="T_73650_row0_col8" class="data row0 col8" >7.5</td>
      <td id="T_73650_row0_col9" class="data row0 col9" >17.5</td>
      <td id="T_73650_row0_col10" class="data row0 col10" >12</td>
      <td id="T_73650_row0_col11" class="data row0 col11" >98.5</td>
    </tr>
    <tr>
      <th id="T_73650_level0_row1" class="row_heading level0 row1" >Cupid's Arrow</th>
      <td id="T_73650_row1_col0" class="data row1 col0" >6</td>
      <td id="T_73650_row1_col1" class="data row1 col1" >14</td>
      <td id="T_73650_row1_col2" class="data row1 col2" >10.5</td>
      <td id="T_73650_row1_col3" class="data row1 col3" >16</td>
      <td id="T_73650_row1_col4" class="data row1 col4" >12</td>
      <td id="T_73650_row1_col5" class="data row1 col5" >9</td>
      <td id="T_73650_row1_col6" class="data row1 col6" >18</td>
      <td id="T_73650_row1_col7" class="data row1 col7" >9.5</td>
      <td id="T_73650_row1_col8" class="data row1 col8" >5</td>
      <td id="T_73650_row1_col9" class="data row1 col9" >2</td>
      <td id="T_73650_row1_col10" class="data row1 col10" >11</td>
      <td id="T_73650_row1_col11" class="data row1 col11" >113</td>
    </tr>
    <tr>
      <th id="T_73650_level0_row2" class="row_heading level0 row2" >天王</th>
      <td id="T_73650_row2_col0" class="data row2 col0" >16.5</td>
      <td id="T_73650_row2_col1" class="data row2 col1" >1</td>
      <td id="T_73650_row2_col2" class="data row2 col2" >8</td>
      <td id="T_73650_row2_col3" class="data row2 col3" >14</td>
      <td id="T_73650_row2_col4" class="data row2 col4" >10</td>
      <td id="T_73650_row2_col5" class="data row2 col5" >7</td>
      <td id="T_73650_row2_col6" class="data row2 col6" >14</td>
      <td id="T_73650_row2_col7" class="data row2 col7" >7</td>
      <td id="T_73650_row2_col8" class="data row2 col8" >1</td>
      <td id="T_73650_row2_col9" class="data row2 col9" >11.5</td>
      <td id="T_73650_row2_col10" class="data row2 col10" >16</td>
      <td id="T_73650_row2_col11" class="data row2 col11" >106</td>
    </tr>
    <tr>
      <th id="T_73650_level0_row3" class="row_heading level0 row3" >JamarrChase</th>
      <td id="T_73650_row3_col0" class="data row3 col0" >5</td>
      <td id="T_73650_row3_col1" class="data row3 col1" >3</td>
      <td id="T_73650_row3_col2" class="data row3 col2" >14</td>
      <td id="T_73650_row3_col3" class="data row3 col3" >12</td>
      <td id="T_73650_row3_col4" class="data row3 col4" >13</td>
      <td id="T_73650_row3_col5" class="data row3 col5" >15</td>
      <td id="T_73650_row3_col6" class="data row3 col6" >15</td>
      <td id="T_73650_row3_col7" class="data row3 col7" >13</td>
      <td id="T_73650_row3_col8" class="data row3 col8" >2</td>
      <td id="T_73650_row3_col9" class="data row3 col9" >7.5</td>
      <td id="T_73650_row3_col10" class="data row3 col10" >14</td>
      <td id="T_73650_row3_col11" class="data row3 col11" >113.5</td>
    </tr>
    <tr>
      <th id="T_73650_level0_row4" class="row_heading level0 row4" >Mars</th>
      <td id="T_73650_row4_col0" class="data row4 col0" >16.5</td>
      <td id="T_73650_row4_col1" class="data row4 col1" >17.5</td>
      <td id="T_73650_row4_col2" class="data row4 col2" >17</td>
      <td id="T_73650_row4_col3" class="data row4 col3" >17</td>
      <td id="T_73650_row4_col4" class="data row4 col4" >18</td>
      <td id="T_73650_row4_col5" class="data row4 col5" >13</td>
      <td id="T_73650_row4_col6" class="data row4 col6" >17</td>
      <td id="T_73650_row4_col7" class="data row4 col7" >5.5</td>
      <td id="T_73650_row4_col8" class="data row4 col8" >7.5</td>
      <td id="T_73650_row4_col9" class="data row4 col9" >3</td>
      <td id="T_73650_row4_col10" class="data row4 col10" >13</td>
      <td id="T_73650_row4_col11" class="data row4 col11" >145</td>
    </tr>
    <tr>
      <th id="T_73650_level0_row5" class="row_heading level0 row5" >max</th>
      <td id="T_73650_row5_col0" class="data row5 col0" >3</td>
      <td id="T_73650_row5_col1" class="data row5 col1" >7</td>
      <td id="T_73650_row5_col2" class="data row5 col2" >4</td>
      <td id="T_73650_row5_col3" class="data row5 col3" >9</td>
      <td id="T_73650_row5_col4" class="data row5 col4" >11</td>
      <td id="T_73650_row5_col5" class="data row5 col5" >14</td>
      <td id="T_73650_row5_col6" class="data row5 col6" >10</td>
      <td id="T_73650_row5_col7" class="data row5 col7" >5.5</td>
      <td id="T_73650_row5_col8" class="data row5 col8" >15</td>
      <td id="T_73650_row5_col9" class="data row5 col9" >5</td>
      <td id="T_73650_row5_col10" class="data row5 col10" >3.5</td>
      <td id="T_73650_row5_col11" class="data row5 col11" >87</td>
    </tr>
    <tr>
      <th id="T_73650_level0_row6" class="row_heading level0 row6" >Melo</th>
      <td id="T_73650_row6_col0" class="data row6 col0" >4</td>
      <td id="T_73650_row6_col1" class="data row6 col1" >15.5</td>
      <td id="T_73650_row6_col2" class="data row6 col2" >10.5</td>
      <td id="T_73650_row6_col3" class="data row6 col3" >11</td>
      <td id="T_73650_row6_col4" class="data row6 col4" >5</td>
      <td id="T_73650_row6_col5" class="data row6 col5" >11</td>
      <td id="T_73650_row6_col6" class="data row6 col6" >7</td>
      <td id="T_73650_row6_col7" class="data row6 col7" >9.5</td>
      <td id="T_73650_row6_col8" class="data row6 col8" >15</td>
      <td id="T_73650_row6_col9" class="data row6 col9" >9</td>
      <td id="T_73650_row6_col10" class="data row6 col10" >7</td>
      <td id="T_73650_row6_col11" class="data row6 col11" >104.5</td>
    </tr>
    <tr>
      <th id="T_73650_level0_row7" class="row_heading level0 row7" >Prince</th>
      <td id="T_73650_row7_col0" class="data row7 col0" >1</td>
      <td id="T_73650_row7_col1" class="data row7 col1" >13</td>
      <td id="T_73650_row7_col2" class="data row7 col2" >16</td>
      <td id="T_73650_row7_col3" class="data row7 col3" >6</td>
      <td id="T_73650_row7_col4" class="data row7 col4" >8.5</td>
      <td id="T_73650_row7_col5" class="data row7 col5" >6</td>
      <td id="T_73650_row7_col6" class="data row7 col6" >4</td>
      <td id="T_73650_row7_col7" class="data row7 col7" >14.5</td>
      <td id="T_73650_row7_col8" class="data row7 col8" >11</td>
      <td id="T_73650_row7_col9" class="data row7 col9" >13</td>
      <td id="T_73650_row7_col10" class="data row7 col10" >8</td>
      <td id="T_73650_row7_col11" class="data row7 col11" >101</td>
    </tr>
    <tr>
      <th id="T_73650_level0_row8" class="row_heading level0 row8" >Sin</th>
      <td id="T_73650_row8_col0" class="data row8 col0" >8</td>
      <td id="T_73650_row8_col1" class="data row8 col1" >8</td>
      <td id="T_73650_row8_col2" class="data row8 col2" >14</td>
      <td id="T_73650_row8_col3" class="data row8 col3" >13</td>
      <td id="T_73650_row8_col4" class="data row8 col4" >4</td>
      <td id="T_73650_row8_col5" class="data row8 col5" >3</td>
      <td id="T_73650_row8_col6" class="data row8 col6" >13</td>
      <td id="T_73650_row8_col7" class="data row8 col7" >4</td>
      <td id="T_73650_row8_col8" class="data row8 col8" >3.5</td>
      <td id="T_73650_row8_col9" class="data row8 col9" >11.5</td>
      <td id="T_73650_row8_col10" class="data row8 col10" >15</td>
      <td id="T_73650_row8_col11" class="data row8 col11" >97</td>
    </tr>
    <tr>
      <th id="T_73650_level0_row9" class="row_heading level0 row9" >72wins</th>
      <td id="T_73650_row9_col0" class="data row9 col0" >7</td>
      <td id="T_73650_row9_col1" class="data row9 col1" >6</td>
      <td id="T_73650_row9_col2" class="data row9 col2" >3</td>
      <td id="T_73650_row9_col3" class="data row9 col3" >2</td>
      <td id="T_73650_row9_col4" class="data row9 col4" >8.5</td>
      <td id="T_73650_row9_col5" class="data row9 col5" >5</td>
      <td id="T_73650_row9_col6" class="data row9 col6" >1</td>
      <td id="T_73650_row9_col7" class="data row9 col7" >17</td>
      <td id="T_73650_row9_col8" class="data row9 col8" >17</td>
      <td id="T_73650_row9_col9" class="data row9 col9" >14</td>
      <td id="T_73650_row9_col10" class="data row9 col10" >1</td>
      <td id="T_73650_row9_col11" class="data row9 col11" >81.5</td>
    </tr>
    <tr>
      <th id="T_73650_level0_row10" class="row_heading level0 row10" >蹩脚马_Alpha</th>
      <td id="T_73650_row10_col0" class="data row10 col0" >10</td>
      <td id="T_73650_row10_col1" class="data row10 col1" >11</td>
      <td id="T_73650_row10_col2" class="data row10 col2" >5.5</td>
      <td id="T_73650_row10_col3" class="data row10 col3" >10</td>
      <td id="T_73650_row10_col4" class="data row10 col4" >7</td>
      <td id="T_73650_row10_col5" class="data row10 col5" >10</td>
      <td id="T_73650_row10_col6" class="data row10 col6" >5</td>
      <td id="T_73650_row10_col7" class="data row10 col7" >2</td>
      <td id="T_73650_row10_col8" class="data row10 col8" >9.5</td>
      <td id="T_73650_row10_col9" class="data row10 col9" >7.5</td>
      <td id="T_73650_row10_col10" class="data row10 col10" >5</td>
      <td id="T_73650_row10_col11" class="data row10 col11" >82.5</td>
    </tr>
    <tr>
      <th id="T_73650_level0_row11" class="row_heading level0 row11" >首席NBA</th>
      <td id="T_73650_row11_col0" class="data row11 col0" >11</td>
      <td id="T_73650_row11_col1" class="data row11 col1" >15.5</td>
      <td id="T_73650_row11_col2" class="data row11 col2" >14</td>
      <td id="T_73650_row11_col3" class="data row11 col3" >5</td>
      <td id="T_73650_row11_col4" class="data row11 col4" >3</td>
      <td id="T_73650_row11_col5" class="data row11 col5" >2</td>
      <td id="T_73650_row11_col6" class="data row11 col6" >12</td>
      <td id="T_73650_row11_col7" class="data row11 col7" >3</td>
      <td id="T_73650_row11_col8" class="data row11 col8" >12</td>
      <td id="T_73650_row11_col9" class="data row11 col9" >17.5</td>
      <td id="T_73650_row11_col10" class="data row11 col10" >18</td>
      <td id="T_73650_row11_col11" class="data row11 col11" >113</td>
    </tr>
    <tr>
      <th id="T_73650_level0_row12" class="row_heading level0 row12" >karsitty</th>
      <td id="T_73650_row12_col0" class="data row12 col0" >18</td>
      <td id="T_73650_row12_col1" class="data row12 col1" >9</td>
      <td id="T_73650_row12_col2" class="data row12 col2" >18</td>
      <td id="T_73650_row12_col3" class="data row12 col3" >18</td>
      <td id="T_73650_row12_col4" class="data row12 col4" >15</td>
      <td id="T_73650_row12_col5" class="data row12 col5" >16</td>
      <td id="T_73650_row12_col6" class="data row12 col6" >16</td>
      <td id="T_73650_row12_col7" class="data row12 col7" >18</td>
      <td id="T_73650_row12_col8" class="data row12 col8" >18</td>
      <td id="T_73650_row12_col9" class="data row12 col9" >1</td>
      <td id="T_73650_row12_col10" class="data row12 col10" >6</td>
      <td id="T_73650_row12_col11" class="data row12 col11" >153</td>
    </tr>
    <tr>
      <th id="T_73650_level0_row13" class="row_heading level0 row13" >灰灰</th>
      <td id="T_73650_row13_col0" class="data row13 col0" >2</td>
      <td id="T_73650_row13_col1" class="data row13 col1" >17.5</td>
      <td id="T_73650_row13_col2" class="data row13 col2" >5.5</td>
      <td id="T_73650_row13_col3" class="data row13 col3" >3</td>
      <td id="T_73650_row13_col4" class="data row13 col4" >1.5</td>
      <td id="T_73650_row13_col5" class="data row13 col5" >1</td>
      <td id="T_73650_row13_col6" class="data row13 col6" >11</td>
      <td id="T_73650_row13_col7" class="data row13 col7" >9.5</td>
      <td id="T_73650_row13_col8" class="data row13 col8" >3.5</td>
      <td id="T_73650_row13_col9" class="data row13 col9" >16</td>
      <td id="T_73650_row13_col10" class="data row13 col10" >17</td>
      <td id="T_73650_row13_col11" class="data row13 col11" >87.5</td>
    </tr>
    <tr>
      <th id="T_73650_level0_row14" class="row_heading level0 row14" >我还想要一只冰墩墩</th>
      <td id="T_73650_row14_col0" class="data row14 col0" >13</td>
      <td id="T_73650_row14_col1" class="data row14 col1" >12</td>
      <td id="T_73650_row14_col2" class="data row14 col2" >12</td>
      <td id="T_73650_row14_col3" class="data row14 col3" >15</td>
      <td id="T_73650_row14_col4" class="data row14 col4" >6</td>
      <td id="T_73650_row14_col5" class="data row14 col5" >12</td>
      <td id="T_73650_row14_col6" class="data row14 col6" >6</td>
      <td id="T_73650_row14_col7" class="data row14 col7" >12</td>
      <td id="T_73650_row14_col8" class="data row14 col8" >9.5</td>
      <td id="T_73650_row14_col9" class="data row14 col9" >6</td>
      <td id="T_73650_row14_col10" class="data row14 col10" >3.5</td>
      <td id="T_73650_row14_col11" class="data row14 col11" >107</td>
    </tr>
    <tr>
      <th id="T_73650_level0_row15" class="row_heading level0 row15" >SLV</th>
      <td id="T_73650_row15_col0" class="data row15 col0" >12</td>
      <td id="T_73650_row15_col1" class="data row15 col1" >5</td>

In [43]:
json = df.to_json()
json

'{"FG%":{"Zephyr":15.0,"Cupid\'s Arrow":6.0,"\\u5929\\u738b":16.5,"JamarrChase":5.0,"Mars":16.5,"max":3.0,"Melo":4.0,"Prince":1.0,"Sin":8.0,"72wins":7.0,"\\u8e69\\u811a\\u9a6c_Alpha":10.0,"\\u9996\\u5e2dNBA":11.0,"karsitty":18.0,"\\u7070\\u7070":2.0,"\\u6211\\u8fd8\\u60f3\\u8981\\u4e00\\u53ea\\u51b0\\u58a9\\u58a9":13.0,"SLV":12.0,"cao\'s Ingenious Team":14.0,"lydia":9.0},"FT%":{"Zephyr":10.0,"Cupid\'s Arrow":14.0,"\\u5929\\u738b":1.0,"JamarrChase":3.0,"Mars":17.5,"max":7.0,"Melo":15.5,"Prince":13.0,"Sin":8.0,"72wins":6.0,"\\u8e69\\u811a\\u9a6c_Alpha":11.0,"\\u9996\\u5e2dNBA":15.5,"karsitty":9.0,"\\u7070\\u7070":17.5,"\\u6211\\u8fd8\\u60f3\\u8981\\u4e00\\u53ea\\u51b0\\u58a9\\u58a9":12.0,"SLV":5.0,"cao\'s Ingenious Team":2.0,"lydia":4.0},"3PTM":{"Zephyr":9.0,"Cupid\'s Arrow":10.5,"\\u5929\\u738b":8.0,"JamarrChase":14.0,"Mars":17.0,"max":4.0,"Melo":10.5,"Prince":16.0,"Sin":14.0,"72wins":3.0,"\\u8e69\\u811a\\u9a6c_Alpha":5.5,"\\u9996\\u5e2dNBA":14.0,"karsitty":18.0,"\\u7070\\u7070":5.5,"\\u6211\\u8fd8\\u60f3\\u8981\\u4e00\\u53ea\\u51b0\\u58a9\\u58a9":12.0,"SLV":7.0,"cao\'s Ingenious Team":1.0,"lydia":2.0},"PTS":{"Zephyr":4.0,"Cupid\'s Arrow":16.0,"\\u5929\\u738b":14.0,"JamarrChase":12.0,"Mars":17.0,"max":9.0,"Melo":11.0,"Prince":6.0,"Sin":13.0,"72wins":2.0,"\\u8e69\\u811a\\u9a6c_Alpha":10.0,"\\u9996\\u5e2dNBA":5.0,"karsitty":18.0,"\\u7070\\u7070":3.0,"\\u6211\\u8fd8\\u60f3\\u8981\\u4e00\\u53ea\\u51b0\\u58a9\\u58a9":15.0,"SLV":8.0,"cao\'s Ingenious Team":1.0,"lydia":7.0},"OREB":{"Zephyr":1.5,"Cupid\'s Arrow":12.0,"\\u5929\\u738b":10.0,"JamarrChase":13.0,"Mars":18.0,"max":11.0,"Melo":5.0,"Prince":8.5,"Sin":4.0,"72wins":8.5,"\\u8e69\\u811a\\u9a6c_Alpha":7.0,"\\u9996\\u5e2dNBA":3.0,"karsitty":15.0,"\\u7070\\u7070":1.5,"\\u6211\\u8fd8\\u60f3\\u8981\\u4e00\\u53ea\\u51b0\\u58a9\\u58a9":6.0,"SLV":16.5,"cao\'s Ingenious Team":14.0,"lydia":16.5},"REB":{"Zephyr":4.0,"Cupid\'s Arrow":9.0,"\\u5929\\u738b":7.0,"JamarrChase":15.0,"Mars":13.0,"max":14.0,"Melo":11.0,"Prince":6.0,"Sin":3.0,"72wins":5.0,"\\u8e69\\u811a\\u9a6c_Alpha":10.0,"\\u9996\\u5e2dNBA":2.0,"karsitty":16.0,"\\u7070\\u7070":1.0,"\\u6211\\u8fd8\\u60f3\\u8981\\u4e00\\u53ea\\u51b0\\u58a9\\u58a9":12.0,"SLV":18.0,"cao\'s Ingenious Team":8.0,"lydia":17.0},"AST":{"Zephyr":2.0,"Cupid\'s Arrow":18.0,"\\u5929\\u738b":14.0,"JamarrChase":15.0,"Mars":17.0,"max":10.0,"Melo":7.0,"Prince":4.0,"Sin":13.0,"72wins":1.0,"\\u8e69\\u811a\\u9a6c_Alpha":5.0,"\\u9996\\u5e2dNBA":12.0,"karsitty":16.0,"\\u7070\\u7070":11.0,"\\u6211\\u8fd8\\u60f3\\u8981\\u4e00\\u53ea\\u51b0\\u58a9\\u58a9":6.0,"SLV":8.0,"cao\'s Ingenious Team":9.0,"lydia":3.0},"ST":{"Zephyr":16.0,"Cupid\'s Arrow":9.5,"\\u5929\\u738b":7.0,"JamarrChase":13.0,"Mars":5.5,"max":5.5,"Melo":9.5,"Prince":14.5,"Sin":4.0,"72wins":17.0,"\\u8e69\\u811a\\u9a6c_Alpha":2.0,"\\u9996\\u5e2dNBA":3.0,"karsitty":18.0,"\\u7070\\u7070":9.5,"\\u6211\\u8fd8\\u60f3\\u8981\\u4e00\\u53ea\\u51b0\\u58a9\\u58a9":12.0,"SLV":14.5,"cao\'s Ingenious Team":1.0,"lydia":9.5},"BLK":{"Zephyr":7.5,"Cupid\'s Arrow":5.0,"\\u5929\\u738b":1.0,"JamarrChase":2.0,"Mars":7.5,"max":15.0,"Melo":15.0,"Prince":11.0,"Sin":3.5,"72wins":17.0,"\\u8e69\\u811a\\u9a6c_Alpha":9.5,"\\u9996\\u5e2dNBA":12.0,"karsitty":18.0,"\\u7070\\u7070":3.5,"\\u6211\\u8fd8\\u60f3\\u8981\\u4e00\\u53ea\\u51b0\\u58a9\\u58a9":9.5,"SLV":6.0,"cao\'s Ingenious Team":13.0,"lydia":15.0},"TO":{"Zephyr":17.5,"Cupid\'s Arrow":2.0,"\\u5929\\u738b":11.5,"JamarrChase":7.5,"Mars":3.0,"max":5.0,"Melo":9.0,"Prince":13.0,"Sin":11.5,"72wins":14.0,"\\u8e69\\u811a\\u9a6c_Alpha":7.5,"\\u9996\\u5e2dNBA":17.5,"karsitty":1.0,"\\u7070\\u7070":16.0,"\\u6211\\u8fd8\\u60f3\\u8981\\u4e00\\u53ea\\u51b0\\u58a9\\u58a9":6.0,"SLV":4.0,"cao\'s Ingenious Team":10.0,"lydia":15.0},"A\\/T":{"Zephyr":12.0,"Cupid\'s Arrow":11.0,"\\u5929\\u738b":16.0,"JamarrChase":14.0,"Mars":13.0,"max":3.5,"Melo":7.0,"Prince":8.0,"Sin":15.0,"72wins":1.0,"\\u8e69\\u811a\\u9a6c_Alpha":5.0,"\\u9996\\u5e2dNBA":18.0,"karsitty":6.0,"\\u7070\\u7070":17.0,"\\u6211\\u8fd8\\u60f3\\u8981\\u4e00\\u53ea\\u51b0\\u58a9\\u58a9":3.5,"SLV":2.0,"cao\'s Ingenious Team":9.0,"lydia":10.0},"Total":{"Zephyr":98.5,"Cupid\'s Arrow":113.0,"\\u5929\\u738b":106.0,"JamarrChase":113.5,"Mars":145.0,"max":87.0,"Melo":104.5,"Prince":101.0,"Sin":97.0,"72wins":81.5,"\\u8e69\\u811a\\u9a6c_Alpha":82.5,"\\u9996\\u5e2dNBA":113.0,"karsitty":153.0,"\\u7070\\u7070":87.5,"\\u6211\\u8fd8\\u60f3\\u8981\\u4e00\\u53ea\\u51b0\\u58a9\\u58a9":107.0,"SLV":101.0,"cao\'s Ingenious Team":82.0,"lydia":108.0}}'